# Generated by ard-make version 1.1

ARDMK_DIR = $(HOME)/Arduino-Makefile
ARDUINO_DIR = $(HOME)/arduino
#BOARDS_TXT = $(HOME)/arduino/hardware/arduino/avr/boards.txt
ARDMK_VENDOR = arduino
BOARD_TAG = mega
BOARD_SUB = atmega2560
#TARGET = Uberprachtige-KBS-game
MONITOR_BAUDRATE = 500000

include $(ARDMK_DIR)/Arduino.mk
